name: First_Workflow1
run-name: "${{ github.actor }}'s Last Workflow Run"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello World"

